# Generated by Django 5.2.14 on 2026-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non Veg'), ('EGG', 'Egg')], default='VEG', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=20, help_text='Preparation time in minutes'),
        ),
    ]
