# Generated by Django 5.2.14 on 2026-07-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('menu', '0002_menuitem_calories_menuitem_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'menu_item')},
        ),
    ]
