# Generated by Django 5.2.14 on 2026-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant_owner', 'Restaurant Owner'), ('delivery_partner', 'Delivery Partner')], default='customer', max_length=20),
        ),
    ]
