# Generated by Django 5.2.14 on 2026-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_image_restaurant_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
