# Generated by Django 5.2.14 on 2026-07-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_deleted_at_restaurant_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
